version: '3.8'

volumes:
  db:
    driver: local

services:
  db:
    image: postgres:15.2
    command: postgres -c 'max_connections=250'
    restart: always
    container_name: 'postgres'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres123}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      # POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 27543:5432
    env_file:
      -  ./dev.env
    volumes:
      - "db:/var/lib/postgresql/data"
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  blockscan:
    image: ghcr.io/magickbase/blockscan:${DOCKER_TAG:-latest}
    depends_on:
      - db
    links:
      - db:database
    restart: always
    container_name: 'blockscan'
    # command: 'elixir --name blockscan@127.0.0.1 -S mix do ecto.create, ecto.migrate, phx.server'
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./dev.env
    ports:
      - 4020:4020


